### ISSUE TITLE
returning error saying arrayagg (or array_agg) does not exist

### ISSUE THREAD

**Issue by easherma** [easherma/mapmystory#3]
![image](https://cloud.githubusercontent.com/assets/10539855/16897933/1e84bc70-4b89-11e6-93e4-3140ab636785.png)

I think ST_AsGeoJSON also doesn't exist as a function. Perhaps an account issue?

**Comment by stuartlynn** [comment]
This should resolve this issue https://github.com/easherma/mapmystory/commit/3405b771530a8c9e9e6e9533f7a31fe82fa0925f#diff-2868fdaa2c106df830bc8cfa0362d1a0

**Comment by easherma** [comment]
"callback is not a function"
